# Generated by Django 5.2 on 2025-04-29 06:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_todo_todomonth_todoweek'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todomonth',
            name='content_month',
        ),
        migrations.RemoveField(
            model_name='todoweek',
            name='content_week',
        ),
        migrations.AddField(
            model_name='todo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todo',
            name='time_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='todomonth',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todomonth',
            name='task',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todomonth',
            name='time_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='todoweek',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todoweek',
            name='task',
            field=models.CharField(default='Default Task', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todoweek',
            name='time_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='todo',
            name='content',
            field=models.CharField(max_length=100),
        ),
    ]
