# Generated by Django 5.2 on 2025-04-29 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_todomonth_content_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomonth',
            name='content_month',
            field=models.CharField(default='Default Task', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todoweek',
            name='content_week',
            field=models.CharField(default='Default Task', max_length=255),
            preserve_default=False,
        ),
    ]
