# Generated by Django 5.2 on 2025-04-29 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_todomonth_content_month_todoweek_content_week'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='time_limit',
            new_name='duration_minutes',
        ),
        migrations.RenameField(
            model_name='todomonth',
            old_name='time_limit',
            new_name='duration_days',
        ),
        migrations.RenameField(
            model_name='todoweek',
            old_name='time_limit',
            new_name='duration_days',
        ),
    ]
