# Generated by Django 5.2 on 2025-04-30 22:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_time_limit_todo_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoweek',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
