# Generated by Django 5.2 on 2025-04-30 22:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_todoweek_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomonth',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
