# Generated by Django 5.2 on 2025-05-01 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_todomonth_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoweek',
            name='content_week',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='todoweek',
            name='duration_days',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='todoweek',
            name='task',
            field=models.CharField(max_length=200),
        ),
    ]
