# Generated by Django 5.2 on 2025-05-01 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_todoweek_content_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomonth',
            name='duration_days',
            field=models.IntegerField(),
        ),
    ]
